// 未整形のSRS
// pritter-ignore
const SRS_TLJSZ = [
    [
        [],
        [
            [
                -1,
                0
            ],
            [
                -1,
                -1
            ],
            [
                0,
                2
            ],
            [
                -1,
                2
            ]
        ],
        [],
        [
            [
                1,
                0
            ],
            [
                1,
                -1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ]
        ]
    ],
    [
        [
            [
                1,
                0
            ],
            [
                1,
                1
            ],
            [
                0,
                -2
            ],
            [
                1,
                -2
            ]
        ],
        [],
        [
            [
                1,
                0
            ],
            [
                1,
                1
            ],
            [
                0,
                -2
            ],
            [
                1,
                -2
            ]
        ],
        []
    ],
    [
        [],
        [
            [
                -1,
                0
            ],
            [
                -1,
                -1
            ],
            [
                0,
                2
            ],
            [
                -1,
                2
            ]
        ],
        [],
        [
            [
                1,
                0
            ],
            [
                1,
                -1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ]
        ]
    ],
    [
        [
            [
                -1,
                0
            ],
            [
                -1,
                1
            ],
            [
                0,
                -2
            ],
            [
                -1,
                -2
            ]
        ],
        [],
        [
            [
                -1,
                0
            ],
            [
                -1,
                1
            ],
            [
                0,
                -2
            ],
            [
                -1,
                -2
            ]
        ],
        []
    ]
]
// pritter-ignore
const SRS_I = [
    [
        [],
        [
            [
                -2,
                0
            ],
            [
                1,
                0
            ],
            [
                -2,
                1
            ],
            [
                1,
                -2
            ]
        ],
        [],
        [
            [
                -1,
                0
            ],
            [
                2,
                0
            ],
            [
                -1,
                -2
            ],
            [
                2,
                1
            ]
        ]
    ],
    [
        [
            [
                2,
                0
            ],
            [
                -1,
                0
            ],
            [
                2,
                -1
            ],
            [
                -1,
                2
            ]
        ],
        [],
        [
            [
                -1,
                0
            ],
            [
                2,
                0
            ],
            [
                -1,
                -2
            ],
            [
                2,
                1
            ]
        ],
        []
    ],
    [
        [],
        [
            [
                1,
                0
            ],
            [
                -2,
                0
            ],
            [
                1,
                2
            ],
            [
                -2,
                -1
            ]
        ],
        [],
        [
            [
                2,
                0
            ],
            [
                -1,
                0
            ],
            [
                2,
                -1
            ],
            [
                -1,
                2
            ]
        ]
    ],
    [
        [
            [
                1,
                0
            ],
            [
                -2,
                0
            ],
            [
                1,
                2
            ],
            [
                -2,
                -1
            ]
        ],
        [],
        [
            [
                -2,
                0
            ],
            [
                1,
                0
            ],
            [
                -2,
                1
            ],
            [
                1,
                -2
            ]
        ],
        []
    ]
]
// ITOLJSZ

function test() {
    // 関数名: compareArray
    // 引数: array1, array2
    // 返り値: array1とarray2が同じ配列かどうか
    // 概要: array1とarray2が同じ配列かどうかを返す
    function compareArray(array1, array2) {
        if (array1.length !== array2.length) return false;
        return array1.every((value, index) => value === array2[index]);
    }

    // 関数名: compareDeepArray
    // 引数: array1, array2, deep
    // 返り値: array1とarray2がdeepまで同じ配列かどうか
    // 概要: array1とarray2がdeepまで同じ配列かどうかを返す
    function compareDeepArray(array1, array2, deep) {
        if (array1.length !== array2.length) return false;
        if (deep === 1) return compareArray(array1, array2);
        return array1.every((value, index) => compareDeepArray(value, array2[index], deep - 1));
    }

    // console.log(compareDeepArray([1, 2, 3], [1, 2, 3], 1)); // true
    // console.log(compareDeepArray([1, 2, 3], [1, 2, 4], 1)); // false
    // console.log(compareDeepArray([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], 2)); // true
    // console.log(compareDeepArray([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 7]], 2)); // false
    // console.log(compareDeepArray([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], 3)); // true
    // console.log(compareDeepArray([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 13]]], 3)); // false

    // console.log(compareDeepArray(SRS_I, SRS_I_, 4));
}
test();
